### ISSUE TITLE
Make sh/edit_postgresql.conf.sh ready to be used as is by anyone

### ISSUE THREAD

**Issue by knightq** [andyatkinson/rideshare#206]
In [`sh/edit_postgresql.conf.sh`](http://media.pragprog.com/titles/aapsql/code/sh/edit_postgresql.conf.sh) referenced on the book, the path is:
- specific to author's home (`andy`).
- specific to the author's preferred editor (`vim`)

I suggest these change in order to have a script ready to be used by anyone, without any change:

```
${EDITOR:-vim} "$HOME/Library/Application Support/Postgres/var-16/postgresql.conf"
```

What do you think?

**Comment by andyatkinson** [comment]
Thanks @knightq. I keep some administration scripts in a separate pg_scripts repo. That file you mentioned is specific to the book, but I took your suggestions and put them in a script.

What do you think of this? https://github.com/andyatkinson/pg_scripts/pull/7

**Comment by knightq** [comment]
Looks even better, thank you @andyatkinson!
