### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by prognostikos** [andyatkinson/rideshare#97]
Hello @andyatkinson 

I am checking this repo out while reading your beta book :)

I can see you have docker-compose files but there's no Dockerfile for the app, is that something that's coming or would you like me to provide one?

**Comment by andyatkinson** [comment]
Hi @prognostikos! Thanks for picking up the book. 😊 I'm not planning to add a Dockerfile right now. If you wanted to add one to your fork and some usage instructions, I'd consider adding it. I know some people prefer to run their dependencies that way. 

The docker compose files are remnants from when this repo was serving a different purpose prior to the book although if they're useful to others and maintained we can keep them around. 

In later chapters readers run pre-built containers using "docker run" directly.

**Comment by andyatkinson** [comment]
I decided to remove the docker-compose files which were created years ago when the repo was used for a different purpose. I didn't want to support those for the time being and they aren't mentioned in the book.

Packaging up the repo as a Dockerfile would be interesting to me but isn't something I'm pursuing now. I'm going to close this for now but if you decide to pursue that, please open a PR and feel free to link to this Issue. Thanks!
